export const SECTOR_SHORT_LABELS: Record<string, string> = {
  A: "Landbouw",
  B: "Delfstoffen",
  C: "Industrie",
  D: "Energie",
  E: "Water en afval",
  F: "Bouw",
  G: "Handel",
  H: "Vervoer",
  I: "Horeca",
  J: "Informatie",
  K: "Financien",
  L: "Vastgoed",
  M: "Vrije beroepen",
  N: "Ondersteunend",
  O: "Overheid",
  P: "Onderwijs",
  Q: "Zorg",
  R: "Kunst en recreatie",
  S: "Overige diensten",
  T: "Huishoudens",
  U: "Extraterritoriaal",
  X: "Onbekend",
}
